# Parameters for your particle filter

motion_params:
  vel_std:    0.05
  delta_std:  0.05
  x_std:      0.02
  y_std:      0.02
  theta_std:  0.05

sensor_params:
  hit_std:    1.0
  z_hit:      0.8
  z_short:    0.03
  z_max:      0.02
  z_rand:     0.15
